---
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        host: '%env(resolve:DATABASE_HOST)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        port: '%env(resolve:DATABASE_PORT)%'
        charset: 'utf8'
        types:
            uuid: App\Infrastructure\Doctrine\Type\UuidType
            account_type: App\Infrastructure\Doctrine\Type\AccountType
            account_name_type: App\Infrastructure\Doctrine\Type\AccountNameType
            account_user_role_type: App\Infrastructure\Doctrine\Type\AccountUserRoleType
            category_type: App\Infrastructure\Doctrine\Type\CategoryType
            transaction_type: App\Infrastructure\Doctrine\Type\TransactionType
            icon_type: App\Infrastructure\Doctrine\Type\IconType
            folder_name_type: App\Infrastructure\Doctrine\Type\FolderNameType
            connection_code_type: App\Infrastructure\Doctrine\Type\ConnectionCodeType
            currency_code_type: App\Infrastructure\Doctrine\Type\CurrencyCodeType
        server_version: 11

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity/mapping'
                prefix: 'App\Domain\Entity'
            Infrastructure:
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity'
                prefix: 'App\Infrastructure\Doctrine\Entity'
