---
monolog:
  channels:
    - 'http_api_exceptions'
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_404s:
        # regex: exclude all 404 errors from the logs
        - ^/
    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: error
      channels:
        - '!http_api_exceptions'
    console:
      type: console
      process_psr_3_messages: false
      channels:
        - '!event'
        - '!doctrine'
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: debug
      channels: ["php"]
    deprecation:
      type: stream
      path: "%kernel.logs_dir%/deprecations.log"
    http_api_exceptions:
      type: stream
      path: '%kernel.logs_dir%/http_api_exceptions.log'
      level: debug
      channels: ['http_api_exceptions']
