---
nelmio_api_doc:
    models:
        use_jms: false
    areas:
        path_patterns:
            - ^/api(?!/doc)
    documentation:
        info:
            title: API documentation
            description: API documentation
            version: 1.0.0
        security:
            - Bearer: []
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    name: Authorization
                    in: header
                    description: 'Authorization: Bearer {jwt}'
            schemas:
                JsonResponseOk:
                    type: object
                    required:
                        - message
                        - data
                    properties:
                        message:
                            type: string
                            description: Information
                        data:
                            type: object
                JsonResponseUnauthorized:
                    type: object
                    required:
                        - code
                        - message
                    properties:
                        code:
                            type: int
                            description: Response code
                        message:
                            type: string
                            description: Information
                JsonResponseError:
                    type: object
                    required:
                        - message
                        - code
                        - errors
                    properties:
                        message:
                            type: string
                            description: Information
                        code:
                            type: integer
                            description: Error code
                        errors:
                            type: array
                            description: Error list
                            items:
                                type: object
                                required:
                                    - key
                                    - message
                                    - code
                                properties:
                                    key:
                                        type: string
                                        description: Error key
                                    message:
                                        type: string
                                        description: Error message
                                    code:
                                        type: string
                                        description: Error code

                JsonResponseException:
                    type: object
                    required:
                        - message
                        - code
                    properties:
                        message:
                            type: string
                            description: Information
                        code:
                            type: integer
                            description: Error code
                        exceptionType:
                            type: string
                            description: Exception type
                        stackTrace:
                            type: object
                            description: Stack trace
