---
nelmio_api_doc:
    models:
        use_jms: false
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        host: 'http://127.0.0.1:%env(resolve:DOCKER_COMPOSE_PORT_NGINX)%'
        info:
            title: API documentation
            description: API documentation
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                name: Authorization
                in: header
                description: 'Authorization: Bearer {jwt}'
        security:
            - Bearer: []
        definitions:
            JsonResponseOk:
                type: object
                required:
                    - message
                    - data
                properties:
                    message:
                        type: string
                        description: Инф. сообщение
                    data:
                        type: object
            JsonResponseError:
                type: object
                required:
                    - message
                    - code
                    - errors
                properties:
                    message:
                        type: string
                        description: Инф. сообщение
                    code:
                        type: integer
                        description: Код ошибки
                    errors:
                        type: array
                        description: Список ошибок
                        items:
                            type: object
                            required:
                                - key
                                - message
                                - code
                            properties:
                                key:
                                    type: string
                                    description: Ключ ошибки
                                message:
                                    type: string
                                    description: Сообщение об ошибке
                                code:
                                    type: string
                                    description: Код ошибки

            JsonResponseException:
                type: object
                required:
                    - message
                    - code
                properties:
                    message:
                        type: string
                        description: Текст ошибки
                    code:
                        type: integer
                        description: Код ошибки
                    exceptionType:
                        type: string
                        description: Тип исключения
                    stackTrace:
                        type: object
                        description: Stack trace
