zenstruck_schedule:
  # The LockFactory service to use for the without overlapping extension
  without_overlapping_lock_factory: lock.local_lock.factory # Example: lock.default.factory

  # The LockFactory service to use for the single server extension - be sure to use a "remote store" (https://symfony.com/doc/current/components/lock.html#remote-stores)
  single_server_lock_factory: lock.remote_lock.factory # Example: lock.redis.factory

  schedule_extensions:
    # Set the environment(s) you only want the schedule to run in.
    environments: [prod]