---
version: '3.5'

services:
    nginx:
        build: ./build/docker/nginx/
        restart: always
        ports:
            - ${DOCKER_COMPOSE_PORT_NGINX}:80
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: ./build/docker/app/Dockerfile
        restart: always
        working_dir: /var/www
        environment:
            - ENVIRONMENT=prod
