---
version: '3.5'

services:
    test:
        build:
            context: .
            dockerfile: ./build/docker/app/Dockerfile
            target: dev
        volumes:
            - .:/var/www:cached
        depends_on:
            - db
        environment:
            - APP_ENV=test
            - COMPOSER_MEMORY_LIMIT=-1
            - PHP_DISPLAY_ERRORS=1
            - PHP_ERROR_REPORTING=32767

#    wiremock:
#        build: ./build/docker/wiremock
#        volumes:
#            - ./app/tests/wiremock/:/home/wiremock
