---
version: '3.5'

services:
    nginx:
        image: ${DOCKER_IMAGE_NGINX}
        restart: always

    app:
        image: ${DOCKER_IMAGE_APP}
        restart: always
        environment:
            - APP_ENV=prod
        networks:
            - infra_net

networks:
    infra_net:
        external: true
