---
monolog:
    handlers:
        main:
            level: error
            action_level: error
            handler: prod
            include_stacktraces: true
        prod:
            type: stream
        deprecation_filter:
            handler: black_hole
#        http_api_exceptions:
#            level: error
        black_hole:
            type: "null"
