---
monolog:
    handlers:
        main:
            action_level: info
        nested:
            level: error
        deprecation:
            level: error
        deprecation_filter:
            max_level: info
        http_api_exceptions:
            level: error
