name: "Build and deploy"
on:
    push:
        branches:
            - master

jobs:
    build_and_deploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Prepare env
                run: |
                    repo=$(echo "${{ github.repository }}" | awk -F / '{print $2}')
                    prefix="${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}"
                    suffix=${{ github.run_id }}
                    echo ::set-env name=DOCKER_IMAGE_NGINX::$(echo "${prefix}/${repo}_nginx:${suffix}")
                    echo ::set-env name=DOCKER_IMAGE_NGINX_LATEST::$(echo "${prefix}/${repo}_nginx:latest")
                    echo ::set-env name=DOCKER_IMAGE_APP::$(echo "${prefix}/${repo}_app:${suffix}")
                    echo ::set-env name=DOCKER_IMAGE_APP_LATEST::$(echo "${prefix}/${repo}_app:latest")
                shell: bash

            -   uses: actions/checkout@v1

            -   name: Docker login
                run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
                env:
                    DOCKER_REGISTRY: 'docker.pkg.github.com'
                    DOCKER_LOGIN: ${{ github.actor }}
                    DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build NGINX image
                if: success()
                run: |
                    docker pull ${DOCKER_IMAGE_NGINX_LATEST} || true
                    docker build --cache-from ${DOCKER_IMAGE_NGINX_LATEST} --tag ${DOCKER_IMAGE_NGINX} --tag ${DOCKER_IMAGE_NGINX_LATEST} -f build/docker/nginx/Dockerfile .
                    docker push ${DOCKER_IMAGE_NGINX}
                    docker push ${DOCKER_IMAGE_NGINX_LATEST}

            -   name: Build APP image
                if: success()
                run: |
                    docker pull ${DOCKER_IMAGE_APP_LATEST} || true
                    docker build --cache-from ${DOCKER_IMAGE_APP_LATEST} --tag ${DOCKER_IMAGE_APP} --tag ${DOCKER_IMAGE_APP_LATEST} --target prod -f build/docker/app/Dockerfile .
                    docker push ${DOCKER_IMAGE_APP}
                    docker push ${DOCKER_IMAGE_APP_LATEST}

            -   id: dotenv
                uses: falti/dotenv-action@v0.2.4
                with:
                    log-variables: true

            -   name: Deploy
                if: success()
                run: |
                    envsubst < docker-compose.production.yml > /tmp/docker-compose.yml
                    cat /tmp/docker-compose.yml
                env:
                    DOCKER_COMPOSE_PORT_NGINX: ${{ steps.dotenv.outputs.docker_compose_port_nginx }}
                    DOCKER_COMPOSE_PORT_DB: ${{ steps.dotenv.outputs.docker_compose_port_db }}
                    DOCKER_COMPOSE_PORT_APP: ${{ steps.dotenv.outputs.docker_compose_port_app }}

            -   uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.DEPLOY_HOST }}
                    username: ${{ secrets.DEPLOY_USERNAME }}
                    key: ${{ secrets.DEPLOY_KEY }}
                    script_stop: true
                    script: |
                        mkdir -p ${{ github.repository }}

            -   uses: garygrossgarten/github-action-scp@release
                with:
                    host: ${{ secrets.DEPLOY_HOST }}
                    username: ${{ secrets.DEPLOY_USERNAME }}
                    privateKey: ${{ secrets.DEPLOY_KEY }}
                    local: "/tmp/docker-compose.yml"
                    remote: "${{ github.repository }}/docker-compose.yml.${{ github.run_id }}"

            -   uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.DEPLOY_HOST }}
                    username: ${{ secrets.DEPLOY_USERNAME }}
                    key: ${{ secrets.DEPLOY_KEY }}
                    script_stop: true
                    script: |
                        rm -f ${{ github.repository }}/docker-compose.yml.backup || true
                        mv ${{ github.repository }}/docker-compose.yml ${{ github.repository }}/docker-compose.yml.backup  || true
                        mv ${{ github.repository }}/docker-compose.yml.${{ github.run_id }} ${{ github.repository }}/docker-compose.yml
                        cd ${{ github.repository }} && docker-compose up -d
#                        cd ${{ github.repository }} && docker-compose exec -uwww-data app bin/console doctrine:migration:migrate -n

            -   name: Cleanup
                if: success()
                run: |
                    rm -f /tmp/docker-compose.yml
#    test:
#        name: Test
#        runs-on: ubuntu-latest
#        env:
#            DOCKER_IMAGE: ${GITHUB_REPOSITORY}:${GITHUB_RUN_ID}
#            DOCKER_IMAGE_LATEST: ${GITHUB_REPOSITORY}:latest
#
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v1
#            - name: Install Task
#              uses: Arduino/actions/setup-taskfile@master
#            - name: Docker login
#              run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
#              env:
#                  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
#                  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
#                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
#            - name: Run tests
#              if: success()
#              run: echo 111
