name: pipeline
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
            NGINX_DOCKER_IMAGE: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}/nginx:${{ github.run_id }}
            NGINX_DOCKER_IMAGE_LATEST: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}/nginx:latest
            APP_DOCKER_IMAGE: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}/app:${{ github.run_id }}
            APP_DOCKER_IMAGE_LATEST: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}/app:latest

        steps:
            - uses: actions/checkout@v1
            - name: Docker login
              run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
              env:
                  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
                  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
            - name: Build NGINX image
              if: success()
              run: |
                docker pull ${NGINX_DOCKER_IMAGE_LATEST} || true
                docker build --cache-from ${NGINX_DOCKER_IMAGE_LATEST} --tag ${NGINX_DOCKER_IMAGE} --tag ${NGINX_DOCKER_IMAGE_LATEST} -f build/docker/nginx/Dockerfile .
                docker push ${NGINX_DOCKER_IMAGE}
                docker push ${NGINX_DOCKER_IMAGE_LATEST}

#    test:
#        name: Test
#        runs-on: ubuntu-latest
#        env:
#            DOCKER_IMAGE: ${GITHUB_REPOSITORY}:${GITHUB_RUN_ID}
#            DOCKER_IMAGE_LATEST: ${GITHUB_REPOSITORY}:latest
#
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v1
#            - name: Install Task
#              uses: Arduino/actions/setup-taskfile@master
#            - name: Docker login
#              run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
#              env:
#                  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
#                  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
#                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
#            - name: Run tests
#              if: success()
#              run: echo 111
