name: pipeline
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
            NGINX_DOCKER_IMAGE: ${GITHUB_REPOSITORY}/nginx:${GITHUB_RUN_ID}
            NGINX_DOCKER_IMAGE_LATEST: ${GITHUB_REPOSITORY}/nginx:latest
            APP_DOCKER_IMAGE: ${GITHUB_REPOSITORY}/app:${GITHUB_RUN_ID}
            APP_DOCKER_IMAGE_LATEST: ${GITHUB_REPOSITORY}/app:latest

        steps:
            - uses: actions/checkout@v1
            - name: Docker login
              run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
              env:
                  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
                  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
            - name: Build NGINX image
              if: success()
              run: |
                docker pull ${DOCKER_IMAGE_LATEST} || true
                docker build --cache-from ${DOCKER_IMAGE_LATEST} --tag ${DOCKER_IMAGE} --tag ${DOCKER_IMAGE_LATEST} -f ${DOCKER_FILE} .
                docker push ${DOCKER_IMAGE}
                docker push ${DOCKER_IMAGE_LATEST}
              env:
                  DOCKER_IMAGE: ${NGINX_DOCKER_IMAGE}
                  DOCKER_IMAGE_LATEST: ${NGINX_DOCKER_IMAGE_LATEST}
                  DOCKER_FILE: "build/docker/nginx/Dockerfile"

#    test:
#        name: Test
#        runs-on: ubuntu-latest
#        env:
#            DOCKER_IMAGE: ${GITHUB_REPOSITORY}:${GITHUB_RUN_ID}
#            DOCKER_IMAGE_LATEST: ${GITHUB_REPOSITORY}:latest
#
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v1
#            - name: Install Task
#              uses: Arduino/actions/setup-taskfile@master
#            - name: Docker login
#              run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
#              env:
#                  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
#                  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
#                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
#            - name: Run tests
#              if: success()
#              run: echo 111
