name: pipeline
on: [push]
jobs:
    test:
        name: Test application
        runs-on: ubuntu-latest
        env:
            DOCKER_IMAGE: ${GITHUB_REPOSITORY}:${GITHUB_RUN_ID}
            DOCKER_IMAGE_LATEST: ${GITHUB_REPOSITORY}:latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install Task
              uses: Arduino/actions/setup-taskfile@master
            - name: Docker login
              run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"
              env:
                  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
                  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
                  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
            - name: Run tests
              if: success()
              run: echo 111
