name: "Test branch"
on:
    push:
        branches:
            - '*'
            - '!master'
            - '!develop'

jobs:
    test-branch:
        name: test_branch
        runs-on: ubuntu-latest
        env:
            DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_IMAGE_APP: "econumo/api-backend:latest"

        services:
            postgresql:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: db_test
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            -   name: Docker login
                run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"

            -   uses: actions/checkout@v3

            -   name: Validate COMPOSER
                if: success()
                run: composer validate

            -   name: Build APP image
                if: success()
                run: |
                    docker pull ${DOCKER_IMAGE_APP} || true
                    docker build --cache-from ${DOCKER_IMAGE_APP} --tag ${DOCKER_IMAGE_APP} --target test -f build/docker/app/Dockerfile .

            -   name: Run tests
                if: success()
                run: |
                    docker run --network="host" --add-host=db:127.0.0.1 ${DOCKER_IMAGE_APP} bin/console doctrine:database:create --if-not-exists --env=test
                    docker run --network="host" --add-host=db:127.0.0.1 ${DOCKER_IMAGE_APP} bin/console doctrine:migration:migrate -n --env=test
                    docker run --network="host" --add-host=db:127.0.0.1 ${DOCKER_IMAGE_APP} bin/console doctrine:fixtures:load --purge-with-truncate -n --env=test
                    docker run --network="host" --add-host=db:127.0.0.1 --env QASE_ENABLE=${QASE_ENABLE} --env QASE_TOKEN=${QASE_TOKEN} --env QASE_PROJECT=${QASE_PROJECT} ${DOCKER_IMAGE_APP} vendor/bin/codecept run
                env:
                    QASE_ENABLE: "false"
                    QASE_TOKEN: ${{ secrets.APP_QASE_TOKEN }}
                    QASE_PROJECT: "EA"

            -   name: Run RECTOR
                if: success()
                run: |
                    docker run --network="host" --add-host=db:127.0.0.1 ${DOCKER_IMAGE_APP} vendor/bin/rector process --dry-run

#            -   name: Run PSALM analysis
#                if: success()
#                run: |
#                    docker run --network="host" --add-host=db:127.0.0.1 ${DOCKER_IMAGE_APP} vendor/bin/psalm --long-progress --output-format=github

